const fallbackText = {
  "common.owner": "Owner",
  "common.age": "Age",
  "common.female": "Female",
  "common.male": "Male",
  "common.month": "Month",
  "common.year": "Year",
  "common.loading": "Loading...",
  "common.retry": "Retry",
  "common.back": "Back",
  "common.uploading": "Uploading...",
  "tracker.gender": "Gender",
  "cowDetails.eyebrow": "Cow Profile",
  "cowDetails.heroText": "Registered cow details, reports, vaccination schedule, and scan history.",
  "cowDetails.fetchFailed": "Failed to load cow details",
  "cowDetails.loading": "Loading cow details...",
  "cowDetails.years": "years",
  "cowDetails.months": "months",
  "cowDetails.milkProduction": "Milk Production",
  "cowDetails.healthReport": "Health Report",
  "cowDetails.reports": "Reports",
  "cowDetails.viewReport": "View reports",
  "cowDetails.addReport": "Add report",
  "cowDetails.scanHistory": "Scan History",
  "cowDetails.scanHistoryText": "All scans stored for this cow.",
  "cowDetails.noScans": "No scans recorded for this cow yet.",
  "cowDetails.confirmDeleteScan": "Delete this scan?",
  "home.na": "N/A",
  "viewAllCows.empty": "No cows registered yet.",
  "viewAllCows.addCow": "Add cow",
  "months.january": "January",
  "months.february": "February",
  "months.march": "March",
  "months.april": "April",
  "months.may": "May",
  "months.june": "June",
  "months.july": "July",
  "months.august": "August",
  "months.september": "September",
  "months.october": "October",
  "months.november": "November",
  "months.december": "December",
};

export function useLanguage() {
  return {
    t: (key, fallback) => fallbackText[key] || fallback || key,
  };
}
